modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "hexlove"
version = "${version}"
displayName = "Hex: Amancy"
logoFile = "assets/hexlove/icon.png"
authors = "Teekas"
description = "Hex: Amancy addon for Hex Casting"

[[dependencies.hexlove]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexlove]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexlove]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexlove]]
modId = "cloth_config"
mandatory = true
versionRange = "[${versions.cloth_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexlove]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexlove]]
modId = "carryon"
mandatory = false
versionRange = "[${versions.carryon},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexlove]]
modId = "curios"
mandatory = false
versionRange = "[${versions.curios},)"
ordering = "AFTER"
side = "BOTH"
