package io.github.teekas.hexlove.client

import com.mojang.blaze3d.systems.RenderSystem
import dev.architectury.event.events.client.ClientGuiEvent
import dev.architectury.event.events.client.ClientPlayerEvent
import dev.architectury.event.events.client.ClientTickEvent
import io.github.teekas.hexlove.Hexlove
import io.github.teekas.hexlove.config.HexloveClientConfig
import io.github.teekas.hexlove.config.HexloveServerConfig
import io.github.teekas.hexlove.nature.ChimeraNatures
import io.github.teekas.hexlove.registry.HexloveEffects
import net.fabricmc.api.EnvType
import net.fabricmc.api.Environment
import net.minecraft.client.Minecraft
import net.minecraft.client.gui.GuiGraphics
import net.minecraft.client.renderer.GameRenderer
import net.minecraft.resources.ResourceLocation
import kotlin.math.roundToInt

/**
 * Requirements 6.4, 9.5, 16.7: the pink and red-pink vignettes, and the gentle turn of the head
 * towards whoever you cannot stop thinking about.
 *
 * Placeholder art on purpose: the vignette is drawn as a stepped gradient inwards from the screen
 * edges rather than from a texture, so it can be replaced by a real one without touching this logic.
 */
@Environment(EnvType.CLIENT)
object HexloveHud {
    private const val LOVE_RGB = 0xFF5FA8
    private const val JEALOUSY_RGB = 0xE00A1C
    private const val HEARTBREAK_RGB = 0x40384A
    private const val PHEROMONE_RGB = 0xFFE6F6
    private const val PHEROMONE_PULSE_TICKS = 40

    /** Mossy leaf green for the serene overlay — a gentle chlorophyll wash on the frame. */
    private const val SERENE_RGB = 0x6AB84A
    /** Deep blood red for the ferocious overlay — reads as blood mist without hiding the world. */
    private const val FEROCIOUS_RGB = 0x9A0F14

    /** Full-screen milky-white radial gradient. Generated by tools/generate_humiliation_cataract.ps1. */
    private val CATARACT_TEXTURE = ResourceLocation(Hexlove.MODID, "textures/gui/humiliation_cataract.png")

    /** Number of bands per screen edge. More is smoother and costs one quad each. */
    private const val STEPS = 20

    fun init() {
        ClientGuiEvent.RENDER_HUD.register { graphics, _ -> render(graphics) }
        ClientTickEvent.CLIENT_POST.register { client ->
            if (ClientBondState.pheromonePulseTicks > 0) ClientBondState.pheromonePulseTicks--
            LoveHeartbeat.tick(client)
            turnHead(client)
        }
        ClientPlayerEvent.CLIENT_PLAYER_QUIT.register { _ ->
            LoveHeartbeat.stop()
            ClientBondState.reset()
        }
    }

    private fun render(graphics: GuiGraphics) {
        val client = Minecraft.getInstance()
        val player = client.player ?: return
        if (client.options.hideGui || client.screen != null && client.screen!!.isPauseScreen) return

        val cfg = HexloveClientConfig.config

        if (ClientBondState.pheromonePulseTicks > 0) {
            val progress = ClientBondState.pheromonePulseTicks.toFloat() / PHEROMONE_PULSE_TICKS
            vignette(graphics, PHEROMONE_RGB, 0.22f * progress * progress)
        }

        // Requirement 4.1: heartbreak outranks love/jealousy overlays, and looks like nothing else.
        // Humiliation is NOT skipped: it must draw on top of everything including heartbreak.
        if (ClientBondState.heartbroken) {
            if (cfg.loveOverlay) vignette(graphics, HEARTBREAK_RGB, OverlayMath.MIN_ALPHA * 1.5f)
            // Fall through so humiliation vignette still draws below.
        } else {
            if (cfg.jealousyOverlay && ClientBondState.hasJealousy) {
                val alpha = OverlayMath.jealousyOverlayAlpha(
                    ClientBondState.jealousyDistance,
                    HexloveServerConfig.config.jealousy.guardRadius,
                )
                vignette(graphics, JEALOUSY_RGB, alpha)
            }

            if (cfg.loveOverlay && ClientBondState.hasLove) {
                val distance = ClientBondState.targetPosition?.distanceTo(player.position())
                val alpha = OverlayMath.loveOverlayAlpha(distance, HexloveServerConfig.config.love.pullDistance)
                vignette(graphics, LOVE_RGB, alpha)
            }
        }

        // Nature overlays — drawn under humiliation so the milky cataract still lands last.
        // Same shape for both natures: a soft whole-screen tint plus an edge vignette so the
        // frame reads as enclosed by the mood.
        if (ChimeraNatures.isSerene(player)) {
            softWash(graphics, SERENE_RGB, 0.06f)
            vignette(graphics, SERENE_RGB, 0.32f)
        } else if (ChimeraNatures.isFerocious(player)) {
            softWash(graphics, FEROCIOUS_RGB, 0.06f)
            vignette(graphics, FEROCIOUS_RGB, 0.32f)
        }

        // Humiliation "cataract": a full-screen milky-white radial gradient PNG, not the stepped
        // vignette used for love/jealousy. It reads vanilla effect sync, no additional packet.
        // Drawn last so it sits on top of every other overlay.
        if (player.hasEffect(HexloveEffects.HUMILIATION.value)) {
            drawCataract(graphics)
        }
    }

    /**
     * Stretches the pre-baked cataract PNG across the whole screen. Uses the vanilla
     * position/tex shader with SrcAlpha/OneMinusSrcAlpha blending so the texture's own alpha
     * decides how much of the world is hidden. The clear window in the centre of the PNG lets
     * the player see just enough directly ahead.
     */
    private fun drawCataract(graphics: GuiGraphics) {
        val width = graphics.guiWidth()
        val height = graphics.guiHeight()

        RenderSystem.enableBlend()
        RenderSystem.defaultBlendFunc()
        RenderSystem.setShader { GameRenderer.getPositionTexShader() }
        RenderSystem.setShaderColor(1f, 1f, 1f, 1f)

        // The last two arguments are the texture size on disk; passing them explicitly stretches
        // the whole thing across [0..width, 0..height] regardless of aspect ratio.
        graphics.blit(CATARACT_TEXTURE, 0, 0, 0f, 0f, width, height, width, height)

        RenderSystem.disableBlend()
    }

    /**
     * A thin whole-screen colour wash of the given RGB at [alpha]. Used for the calm serene tint
     * and the base layer of the ferocious blood overlay.
     */
    private fun softWash(graphics: GuiGraphics, rgb: Int, alpha: Float) {
        val a = (alpha * 255f).roundToInt().coerceIn(0, 255)
        if (a == 0) return
        graphics.fill(0, 0, graphics.guiWidth(), graphics.guiHeight(), (a shl 24) or rgb)
    }

    /** Bands of decreasing alpha marching in from each edge. Cheap, and reads as a vignette. */
    private fun vignette(graphics: GuiGraphics, rgb: Int, alpha: Float) {
        if (alpha <= 0f) return
        val width = graphics.guiWidth()
        val height = graphics.guiHeight()
        val depth = (minOf(width, height) * 0.4).roundToInt().coerceAtLeast(STEPS)
        val band = (depth / STEPS).coerceAtLeast(1)

        for (step in 0 until STEPS) {
            // full strength at the edge, nothing at the inner end
            val fade = 1f - step.toFloat() / STEPS
            val a = (alpha * fade * fade * 255f).roundToInt().coerceIn(0, 255)
            if (a == 0) continue
            val color = (a shl 24) or rgb

            val near = step * band
            val far = near + band
            graphics.fill(0, near, width, far, color)
            graphics.fill(0, height - far, width, height - near, color)
            graphics.fill(near, far, far, height - far, color)
            graphics.fill(width - far, far, width - near, height - far, color)
        }
    }

    /**
     * Requirement 9.8: a nudge, never a snap — you can always look away, you just keep drifting back.
     * Requirement 20, revised: the siren is different. Its song *holds* the gaze on the caller.
     */
    private fun turnHead(client: Minecraft) {
        val player = client.player ?: return
        if (ClientBondState.heartbroken) return

        val sirenCfg = HexloveServerConfig.config.siren
        val sirenPos = ClientBondState.sirenPosition
        if (ClientBondState.hasSiren && sirenPos != null && sirenCfg.lockPlayerView) {
            val eye = player.eyePosition
            player.yRot += OverlayMath.cameraNudge(player.yRot, OverlayMath.yawTowards(eye, sirenPos), 0.5f)
            player.xRot += (OverlayMath.pitchTowards(eye, sirenPos) - player.xRot) * 0.5f
            player.yHeadRot = player.yRot
            return
        }

        if (!HexloveClientConfig.config.smoothCameraNudge) return
        val target = ClientBondState.targetPosition ?: return
        if (!ClientBondState.hasLove) return

        val pullDistance = HexloveServerConfig.config.love.pullDistance
        if (player.position().distanceTo(target) <= pullDistance) return

        player.yRot += OverlayMath.cameraNudge(player.yRot, OverlayMath.yawTowards(player.eyePosition, target), 0.03f)
    }
}
